DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(255)		NOT NULL,
	"BOARD_VIEWS"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_MODIFY_TIME"	DATE		NULL,
	"BOARD_TYPE"	VARCHAR2(20)		NOT NULL,
	"BOARD_COVER_SRC"	VARCHAR2(255)		NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"FILTER_TYPE"	VARCHAR2(20)		NOT NULL,
	"FILTER_AREA"	NUMBER		NOT NULL,
	"FILTER_NUM"	NUMBER		NULL,
	"FILTER_DIRECTION"	VARCHAR2(20)		NULL,
	"FILTER_PAST"	VARCHAR2(20)		NULL,
	"FILTER_LOCAL"	VARCHAR2(255)		NULL,
	"FILTER_FAMILY"	VARCHAR2(255)		NOT NULL,
	"FILTER_PET"	VARCHAR2(20)		NULL,
	"FILTER_FAMILY_MEM_CNT"	NUMBER		NULL,
	"FILTER_FIELD"	VARCHAR2(20)		NULL,
	"FILTER_WORKER"	VARCHAR2(20)		NOT NULL,
	"FILTER_RANGE"	VARCHAR2(20)		NULL,
	"FILTER_PERIOD"	NUMBER		NULL,
	"FILTER_PERIOD_TYPE"	VARCHAR2(20)		NULL,
	"FILTER_CONSTRUCTION_PRICE"	NUMBER		NULL,
	"FILTER_STYLE_PRICE"	NUMBER		NULL,
	"FILTER_URL"	VARCHAR2(255)		NULL,
	"FILTER_COPYRIGHT"	VARCHAR2(20)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시글ID';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_VIEWS" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_CREATE_TIME" IS '생성일';

COMMENT ON COLUMN "BOARD"."BOARD_MODIFY_TIME" IS '수정일';

COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '게시글 타입';

COMMENT ON COLUMN "BOARD"."BOARD_COVER_SRC" IS '커버 사진 주소';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '내용';

COMMENT ON COLUMN "BOARD"."FILTER_TYPE" IS '주거형태';

COMMENT ON COLUMN "BOARD"."FILTER_AREA" IS '평수';

COMMENT ON COLUMN "BOARD"."FILTER_NUM" IS '방개수';

COMMENT ON COLUMN "BOARD"."FILTER_DIRECTION" IS '방향';

COMMENT ON COLUMN "BOARD"."FILTER_PAST" IS '준공연차';

COMMENT ON COLUMN "BOARD"."FILTER_LOCAL" IS '지역';

COMMENT ON COLUMN "BOARD"."FILTER_FAMILY" IS '가족형태';

COMMENT ON COLUMN "BOARD"."FILTER_PET" IS '반려동물';

COMMENT ON COLUMN "BOARD"."FILTER_FAMILY_MEM_CNT" IS '구성원수';

COMMENT ON COLUMN "BOARD"."FILTER_FIELD" IS '작업분야';

COMMENT ON COLUMN "BOARD"."FILTER_WORKER" IS '작업자';

COMMENT ON COLUMN "BOARD"."FILTER_RANGE" IS '시공범위';

COMMENT ON COLUMN "BOARD"."FILTER_PERIOD" IS '기간';

COMMENT ON COLUMN "BOARD"."FILTER_PERIOD_TYPE" IS '주 또는 개월';

COMMENT ON COLUMN "BOARD"."FILTER_CONSTRUCTION_PRICE" IS '공사 예산';

COMMENT ON COLUMN "BOARD"."FILTER_STYLE_PRICE" IS '스타일링예산';

COMMENT ON COLUMN "BOARD"."FILTER_URL" IS '링크';

COMMENT ON COLUMN "BOARD"."FILTER_COPYRIGHT" IS '저작권자';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

DROP TABLE "PRODUCT";

CREATE TABLE "PRODUCT" (
	"PRODUCT_ID"	NUMBER		NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(100)		NOT NULL,
	"PRODUCT_PRICE"	VARCHAR(255)		NULL,
	"PRODUCT_SALES"	VARCHAR(255)		NULL,
	"AMOUNT"	VARCHAR(255)		NULL,
	"ARRIVAL_DATE"	VARCHAR(255)		NULL,
	"SALE"	NUMBER		NULL,
	"PRODUCT_THUMBNAIL"	VARCHAR2(255)		NOT NULL,
	"PRODUCT_IMG"	VARCHAR2(255)		NOT NULL,
	"PRODUCT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"PRODUCT_CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PRODUCT_MODIFY_TIME"	DATE		NULL,
	"CATEGORY_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PRODUCT_DELIVERY_PRICE"	NUMBER	DEFAULT 0	NULL
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_PRICE" IS '가격';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_SALES" IS '누적판매량';

COMMENT ON COLUMN "PRODUCT"."AMOUNT" IS '재고수량';

COMMENT ON COLUMN "PRODUCT"."ARRIVAL_DATE" IS '배송완료일';

COMMENT ON COLUMN "PRODUCT"."SALE" IS '할인율';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_THUMBNAIL" IS '썸네일이미지';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_IMG" IS '상품이미지';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_CONTENT" IS '상품내용';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_CREATE_TIME" IS '생성일';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_MODIFY_TIME" IS '수정일';

COMMENT ON COLUMN "PRODUCT"."CATEGORY_ID" IS '카테고리ID';

COMMENT ON COLUMN "PRODUCT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_DELIVERY_PRICE" IS '배송비';

DROP TABLE "PRODUCT_OPTIONS";

CREATE TABLE "PRODUCT_OPTIONS" (
	"PRODUCT_OPTIONS_ID"	NUMBER		NOT NULL,
	"PRODUCT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"PRODUCT_PRICE"	NUMBER		NOT NULL,
	"PRODUCT_OPTIONS_STOCK"	NUMBER		NOT NULL,
	"PRODUCT_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_ID" IS '상품옵션ID';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_CONTENT" IS '옵션내용';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_PRICE" IS '옵션가격';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_STOCK" IS '옵션재고';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_ID" IS '상품ID';

DROP TABLE "ORDER";

CREATE TABLE "ORDER" (
	"ORDER_ID"	NUMBER		NOT NULL,
	"RECIPIENT_NAME"	VARCHAR2(20)		NOT NULL,
	"RECIPIENT_PHONE"	VARCHAR2(50)		NOT NULL,
	"RECIPIENT_EMAIL"	VARCHAR2(255)		NULL,
	"RECIPIENT_ADDRESS"	VARCHAR(255)		NOT NULL,
	"RECIPIENT_POSTCODE"	NUMBER		NOT NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ORDER_AMOUNT"	NUMBER		NOT NULL,
	"PAYMENT_AMOUNT"	NUMBER		NOT NULL,
	"ORDER_DELIVERY_DATE"	DATE		NOT NULL,
	"REQURIEDMENT"	VARCHAR2(255)		NULL,
	"PRODUCT_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ORDER_DELIVERY_STATUS"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_ID" IS '주문번호';

COMMENT ON COLUMN "ORDER"."RECIPIENT_NAME" IS '수령인';

COMMENT ON COLUMN "ORDER"."RECIPIENT_PHONE" IS '수령인전화번호';

COMMENT ON COLUMN "ORDER"."RECIPIENT_EMAIL" IS '수령인이메일';

COMMENT ON COLUMN "ORDER"."RECIPIENT_ADDRESS" IS '수령인주소';

COMMENT ON COLUMN "ORDER"."RECIPIENT_POSTCODE" IS '수령인우편번호';

COMMENT ON COLUMN "ORDER"."ORDER_DATE" IS '주문일자';

COMMENT ON COLUMN "ORDER"."ORDER_AMOUNT" IS '주문수량';

COMMENT ON COLUMN "ORDER"."PAYMENT_AMOUNT" IS '지불금액';

COMMENT ON COLUMN "ORDER"."ORDER_DELIVERY_DATE" IS '배송완료일';

COMMENT ON COLUMN "ORDER"."REQURIEDMENT" IS '요청사항';

COMMENT ON COLUMN "ORDER"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "ORDER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "ORDER"."ORDER_DELIVERY_STATUS" IS '배송상태';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PWD"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_BIRTH"	DATE		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(20)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"MEMBER_TYPE"	VARCHAR2(20)		NOT NULL,
	"COMPANY_NAME"	VARCHAR2(255)		NOT NULL,
	"REPRESENTATATIVE"	VARCHAR2(20)		NOT NULL,
	"COMPANY_PLACE"	VARCHAR2(255)		NOT NULL,
	"COMPANY_PHONE"	VARCHAR2(20)		NOT NULL,
	"COMPANY_EMAIL"	VARCHAR2(255)		NOT NULL,
	"REG_NUM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PWD" IS '회원비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '회원생년월일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "MEMBER"."GENDER" IS '회원성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_TYPE" IS '회원타입';

COMMENT ON COLUMN "MEMBER"."COMPANY_NAME" IS '상호';

COMMENT ON COLUMN "MEMBER"."REPRESENTATATIVE" IS '대표자';

COMMENT ON COLUMN "MEMBER"."COMPANY_PLACE" IS '사업장소재지';

COMMENT ON COLUMN "MEMBER"."COMPANY_PHONE" IS '회사전화번호';

COMMENT ON COLUMN "MEMBER"."COMPANY_EMAIL" IS '회사이메일';

COMMENT ON COLUMN "MEMBER"."REG_NUM" IS '사업자등록번호';

DROP TABLE "PRODUCT_BASKET";

CREATE TABLE "PRODUCT_BASKET" (
	"PRODUCT_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"QUANTITY"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PRODUCT_BASKET"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "PRODUCT_BASKET"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PRODUCT_BASKET"."QUANTITY" IS '수량';

DROP TABLE "QNA";

CREATE TABLE "QNA" (
	"QNA_ID"	NUMBER		NOT NULL,
	"QNA_ISSUE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"QNA_CONTENT"	VARCHAR2(4000)		NULL,
	"QNA_TYPE"	CHAR(1)	DEFAULT 'Q'	NOT NULL,
	"QNA_CONFIDENTIAL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PRODUCT_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "QNA"."QNA_ID" IS '질답ID';

COMMENT ON COLUMN "QNA"."QNA_ISSUE_DATE" IS '작성일';

COMMENT ON COLUMN "QNA"."QNA_CONTENT" IS '내용';

COMMENT ON COLUMN "QNA"."QNA_TYPE" IS '질답타입';

COMMENT ON COLUMN "QNA"."QNA_CONFIDENTIAL" IS '비밀글여부';

COMMENT ON COLUMN "QNA"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "QNA"."MEMBER_NO" IS '회원번호';

DROP TABLE "BOARD_MEDIA";

CREATE TABLE "BOARD_MEDIA" (
	"MEDIA_ID"	NUMBER		NOT NULL,
	"MEDIA_TYPE"	VARCHAR2(20)		NOT NULL,
	"MEDIA_SRC"	VARCHAR2(255)		NOT NULL,
	"BOARD_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_MEDIA"."MEDIA_ID" IS '미디어ID';

COMMENT ON COLUMN "BOARD_MEDIA"."MEDIA_TYPE" IS '사진 동영상';

COMMENT ON COLUMN "BOARD_MEDIA"."MEDIA_SRC" IS '미디어 주소';

COMMENT ON COLUMN "BOARD_MEDIA"."BOARD_ID" IS '게시글ID';

DROP TABLE "REPLY";

CREATE TABLE "REPLY" (
	"REPLY_ID"	NUMBER		NOT NULL,
	"REPLY_TEXT"	VARCHAR2(4000)		NOT NULL,
	"REPLY_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPLY_MODIFT_DATE"	DATE		NULL,
	"BOARD_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_ID" IS '댓글ID';

COMMENT ON COLUMN "REPLY"."REPLY_TEXT" IS '댓글 텍스트';

COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DATE" IS '생성일';

COMMENT ON COLUMN "REPLY"."REPLY_MODIFT_DATE" IS '수정일';

COMMENT ON COLUMN "REPLY"."BOARD_ID" IS '게시글ID';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원번호';

DROP TABLE "REVIEW";

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	NUMBER		NOT NULL,
	"RATING"	NUMBER		NOT NULL,
	"REVIEW_IMG"	VARCHAR2(255)		NOT NULL,
	"REVIEW_DETAIL"	VARCHAR2(4000)		NOT NULL,
	"HELPFUL"	VARCHAR(255)		NULL,
	"REVIEW_CREATE_DAY"	DATE		NOT NULL,
	"REVIEW_MODIFT_DAY"	DATE		NULL,
	"PRODUCT_ID"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '리뷰ID';

COMMENT ON COLUMN "REVIEW"."RATING" IS '별점';

COMMENT ON COLUMN "REVIEW"."REVIEW_IMG" IS '리뷰이미지';

COMMENT ON COLUMN "REVIEW"."REVIEW_DETAIL" IS '리뷰내용';

COMMENT ON COLUMN "REVIEW"."HELPFUL" IS '도움이돼요';

COMMENT ON COLUMN "REVIEW"."REVIEW_CREATE_DAY" IS '생성일';

COMMENT ON COLUMN "REVIEW"."REVIEW_MODIFT_DAY" IS '수정일';

COMMENT ON COLUMN "REVIEW"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "REVIEW"."MEMBER_NO" IS '회원번호';

DROP TABLE "TAG";

CREATE TABLE "TAG" (
	"MEDIA_ID"	NUMBER		NOT NULL,
	"PRODUCT_ID"	NUMBER		NOT NULL,
	"TAG_X"	NUMBER		NULL,
	"TAG_Y"	NUMBER		NULL
);

COMMENT ON COLUMN "TAG"."MEDIA_ID" IS '미디어ID';

COMMENT ON COLUMN "TAG"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "TAG"."TAG_X" IS '태그  X  좌표';

COMMENT ON COLUMN "TAG"."TAG_Y" IS '태그 Y 좌표';

DROP TABLE "CATEGORY";

CREATE TABLE "CATEGORY" (
	"CATEGORY_ID"	NUMBER		NOT NULL,
	"CATEGORY_SHOPPING"	VARCHAR2(30)		NOT NULL,
	"CATEGORY_PRODUCT"	VARCHAR2(30)		NOT NULL,
	"CATEGORY_FURNITURE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_ID" IS '카테고리ID';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_SHOPPING" IS '쇼핑카테고리';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_PRODUCT" IS '상품카테고리';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_FURNITURE" IS '가구카테고리';

DROP TABLE "SCRAP";

CREATE TABLE "SCRAP" (
	"SCRAP_ID"	NUMBER		NOT NULL,
	"SCRAP_TYPE"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_ID"	NUMBER		NOT NULL,
	"MEDIA_ID"	NUMBER		NOT NULL,
	"PRODUCT_ID"	NUMBER		NOT NULL,
	"SCRAP_CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"SCRAP_MODIFY_TIME"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "SCRAP"."SCRAP_ID" IS '스크랩ID';

COMMENT ON COLUMN "SCRAP"."SCRAP_TYPE" IS '스크랩타입';

COMMENT ON COLUMN "SCRAP"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "SCRAP"."BOARD_ID" IS '게시글ID';

COMMENT ON COLUMN "SCRAP"."MEDIA_ID" IS '미디어ID';

COMMENT ON COLUMN "SCRAP"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "SCRAP"."SCRAP_CREATE_TIME" IS '스크랩생성일';

COMMENT ON COLUMN "SCRAP"."SCRAP_MODIFY_TIME" IS '스크랩수정일';

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_ID"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRODUCT_ID"
);

ALTER TABLE "PRODUCT_OPTIONS" ADD CONSTRAINT "PK_PRODUCT_OPTIONS" PRIMARY KEY (
	"PRODUCT_OPTIONS_ID"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "PRODUCT_BASKET" ADD CONSTRAINT "PK_PRODUCT_BASKET" PRIMARY KEY (
	"PRODUCT_ID",
	"MEMBER_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_ID"
);

ALTER TABLE "BOARD_MEDIA" ADD CONSTRAINT "PK_BOARD_MEDIA" PRIMARY KEY (
	"MEDIA_ID"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY (
	"MEDIA_ID",
	"PRODUCT_ID"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY_ID"
);

ALTER TABLE "SCRAP" ADD CONSTRAINT "PK_SCRAP" PRIMARY KEY (
	"SCRAP_ID"
);

ALTER TABLE "PRODUCT_BASKET" ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_BASKET_1" FOREIGN KEY (
	"PRODUCT_ID"
)
REFERENCES "PRODUCT" (
	"PRODUCT_ID"
);

ALTER TABLE "PRODUCT_BASKET" ADD CONSTRAINT "FK_MEMBER_TO_PRODUCT_BASKET_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TAG" ADD CONSTRAINT "FK_BOARD_MEDIA_TO_TAG_1" FOREIGN KEY (
	"MEDIA_ID"
)
REFERENCES "BOARD_MEDIA" (
	"MEDIA_ID"
);

ALTER TABLE "TAG" ADD CONSTRAINT "FK_PRODUCT_TO_TAG_1" FOREIGN KEY (
	"PRODUCT_ID"
)
REFERENCES "PRODUCT" (
	"PRODUCT_ID"
);

